### PR TITLE
add Laravel 10 support

### PR DESCRIPTION
**Pull request by bensherred**
This PR adds support Laravel 10.

### CODE REVIEW

**Comment by bensherred** [comment]
Hey @bezhermoso or @bmish, would it be possible to get a review on this?

**Comment by bezhermoso** [comment]
Hi @bensherred, thank you for your contribution! I'll work on getting this as a release. Apologies for the delay!

**Comment by bensherred** [comment]
Thanks @bezhermoso, if it's helpful, I ended up doing a fork here: https://github.com/red-explosion/vermillion

There might have been a couple of extra bits I changed

**Comment by bezhermoso** [comment]
That's cool! Interested in moving them back upstream?

**Pull request merged**
